CREATE SEQUENCE IF NOT EXISTS ingredient_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE ingredient
(
    id       INTEGER DEFAULT nextval('ingredient_seq') PRIMARY KEY,
    name     VARCHAR(255),
    quantity INTEGER,
    unit     VARCHAR(255)
);

CREATE TABLE recette
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    rate DOUBLE PRECISION,
    date date,
    CONSTRAINT pk_recette PRIMARY KEY (id)
);

CREATE TABLE recette_ingredients
(
    recette_id     INTEGER NOT NULL,
    ingredients_id INTEGER NOT NULL
);

CREATE TABLE recette_steps (
    recette_id INTEGER NOT NULL,
    steps VARCHAR(255),
    CONSTRAINT fk_recette_steps_recette FOREIGN KEY (recette_id) REFERENCES recette(id)
);

CREATE TABLE recette_tags (
    recette_id INTEGER NOT NULL,
    tags VARCHAR(255),
    CONSTRAINT fk_recette_tags_recette FOREIGN KEY (recette_id) REFERENCES recette(id)
);

ALTER TABLE recette_ingredients
    ADD CONSTRAINT uc_recette_ingredients_ingredients UNIQUE (ingredients_id);

ALTER TABLE recette_ingredients
    ADD CONSTRAINT fk_recing_on_ingredient FOREIGN KEY (ingredients_id) REFERENCES ingredient (id);

ALTER TABLE recette_ingredients
    ADD CONSTRAINT fk_recing_on_recette FOREIGN KEY (recette_id) REFERENCES recette (id);